### ISSUE TITLE
Slots not appearing

### ISSUE THREAD

**Issue by mythdigital** [ethercreative/bookings#20]
Hi guys,

We're using this on a live build at the moment and seem to be having issues with slots appearing. It looks to be slightly buggy and only shows some dates. We had this issue before and added .limit(NULL) to the loop – which fixed the dates at that time. 

However, now some dates just aren't appearing. I've attached two screenshots, screenshot 1 shows there are slots for 22/11/18 and on the front-end (screenshot 2) it's only showing one date. 

Let me know what you need from our build to help debug.

This is our loop;
`{% set slots = craft.availability(course.courseInterviewSlots).limit(null).all() %}`

<img width="370" alt="screen shot 2018-10-30 at 15 03 55" src="https://user-images.githubusercontent.com/33261341/47727908-37b8f800-dc55-11e8-8363-6aac917f557a.png">

<img width="818" alt="screen shot 2018-10-30 at 15 03 10" src="https://user-images.githubusercontent.com/33261341/47727756-f1639900-dc54-11e8-81b6-2f3623148e5d.png">

**Comment by Tam** [comment]
Closed following slack discussion.
